#!/usr/bin/env bash

case "$1" in
  -m)
    php modules/.tracem.php
    ;;
  -t)
    if [ "$#" -eq 2 ]; then
      php modules/.traceip.php "$2"
    else
      echo "error: invalid arguments!!"
      echo "usage: trace -t <target_ip>"
      exit 1
    fi
    ;;
  -u|update)
    php modules/.update.php
    exit
    ;;
  start)
    php .IP-Tracer.php
    exit
    ;;
  -rm)
    php modules/.uninstall.php
    exit
    ;;
  -h|help)
    php modules/.help.php
    exit
    ;;
  *)
    echo "Usage: trace [command]... [arguments]..."
    echo " Commands:"
    echo " -t <target_ip>      to trace target ip."
    echo " -m                  to trace your own ip."
    echo " -h, help            to show help."
    echo " -u, update          to update ip-tracer."
    echo " start               to start ip-tracer menu."
    echo " -rm                 to uninstall ip-tracer."
    exit 1
    ;;
esac
